Add Custom Database Parameter Loader
nautobot/nautobot-plugin-ssot pull request #281
Opened 2023-11-27 15:57 UTC by Renrut5

Problem:
As it currently stands, trying to sync the `time_zone` field in `Location` objects from Nautobot does not appear to be supported.
- Loading objects from the database returns a `DstTzInfo` object
- `DstTzInfo` is not JSON serializable and raises an error when used, so cannot be used for SSoT
- Unable to determine existing way to convert the `DstTzInfo` object into a string which can be compared within SSoT
- Unable to override an individual field when loading from the Nautobot adapter

Solution:
This PR provides two solutions:
1. A way for any child class of `NautobotAdapter` to add additional methods to override the default loading of individual fields/parameters (excluding custom fields and relationships). It searches for a method named `load_param_{param_name}`
2. A method for handling the `time_zone` field by converting the `DstTzInfo` class into a string enabling default handling of the `time_zone` field. Any parameter or field without a specified method will be get default handling

2023-11-29 20:02 UTC, Renrut5 commented
@jdrew82 I just updated the initial comment with details

2023-12-01 12:05 UTC, Kircheneer commented
Couple thoughts:
- It would be cool to have a unit test for this behaviour
- The parameter may not necessarily be called `time_zone` - I have two separate approaches in mind to remedy this
    - EITHER: Don't provide any default implementation for any `load_param` function and provide the time zone example in the docs
    - OR: Use `typing.Annotate` to map this

I think for now I prefer the EITHER approach, what do you think?

2023-12-05 15:36 UTC, Renrut5 commented
@Kircheneer 

> * The parameter may not necessarily be called `time_zone` - I have two separate approaches in mind to remedy this

This is in the default `NautobotAdapter` class, so the it should always be `time_zone` unless I'm missing something. Not sure how it would be mapped if done with that approach.

2023-12-05 15:47 UTC, Kircheneer commented
> @Kircheneer
> 
> > * The parameter may not necessarily be called `time_zone` - I have two separate approaches in mind to remedy this
> 
> This is in the default `NautobotAdapter` class, so the it should always be `time_zone` unless I'm missing something. Not sure how it would be mapped if done with that approach.

This depends on the model - for some existing core model it may be literally called `time_zone` but we need to take into account the possibility of future plugin models whose time zone fields may not literally be called `time_zone`

2023-12-08 21:40 UTC, Renrut5 commented
@Kircheneer , I updated based on your suggestions. The default `time_zone` was removed and used in the documentation instead.

2023-12-11 13:16 UTC, Kircheneer approved these changes
LGTM, @jdrew82 what do you think?

2023-12-11 14:20 UTC, jdrew82 requested changes
Just one correction to make and then I think it's g2g.

2023-12-11 14:20 UTC, jdrew82 commented on docs/dev/jobs.md
Why was the extra line removed here? There are supposed to be two lines between imports and the top most function/class.

2023-12-11 21:58 UTC, Renrut5 commented
@jdrew82 my mistake, I missed that. Fixed and pushed.

2023-12-11 23:29 UTC, jdrew82 approved these changes
LGTM!

2023-12-11 23:29 UTC, merged